service: twitch-data-collector
provider:
  name: aws
  runtime: nodejs6.10
functions:
  captureCurrentGames:
    handler: handler.captureCurrentGames
    events:
      # Every hour
      - schedule: cron(* * * * * *)

